"""Add resume_file_path column

Revision ID: 75832e35b3b8
Revises: 
Create Date: 2026-07-20 16:02:21.849861

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75832e35b3b8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('resume_file_path', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profile', schema=None) as batch_op:
        batch_op.drop_column('resume_file_path')

    # ### end Alembic commands ###
